// AYBGFXConverter.cpp - BGFX backend converter implementation

#include "AYBGFXConverter.h"
#include "AYAst.h"
#include <sstream>

namespace ayt::shader
{

BGFXConvertResult AYBGFXConverter::convertBGFX(const phoskia::Program& ast) {
    BGFXConvertResult result;
    result.shaderType = _shaderType;

    try {
        result.output = generateSC(ast);
        result.uniforms = _uniforms;
        result.textures = _textures;
        result.success = true;
    } catch (const std::exception& e) {
        result.errors.push_back(e.what());
    }

    return result;
}

ConvertResult AYBGFXConverter::convert(const phoskia::Program& ast) {
    ConvertResult result;
    auto bgfxResult = convertBGFX(ast);
    result.success = bgfxResult.success;
    result.output = bgfxResult.output;
    result.errors = bgfxResult.errors;
    // Forward BGFX uniform / texture info to the generic result.
    for (const auto& u : bgfxResult.uniforms) {
        result.uniforms.emplace_back(u.name, u.type);
    }
    for (const auto& t : bgfxResult.textures) {
        result.textures.emplace_back(t.name, t.binding);
    }
    return result;
}

std::string AYBGFXConverter::generateSC(const phoskia::Program& ast) {
    _output.clear();
    _uniforms.clear();
    _textures.clear();

    // BGFX .sc header
    _output += "// Generated by AYShader/Phoskia\n";
    _output += "// Target: BGFX .sc format\n\n";

    // Process all material declarations
    for (const auto& decl : ast.declarations) {
        if (auto material = dynamic_cast<const phoskia::MaterialDecl*>(decl.get())) {
            generateShaderBlock(*material, _shaderType == BGFXShaderType::Vertex);
        }
    }

    return _output;
}

void AYBGFXConverter::generateShaderBlock(const phoskia::MaterialDecl& material, bool isVertex) {
    std::string blockName = isVertex ? "vertex" : "fragment";

    _output += "[" + blockName + "]\n";
    _output += "[" + material.name + "]\n\n";

    // First pass: collect uniforms, textures
    for (const auto& item : material.declarations) {
        if (auto uniform = dynamic_cast<const phoskia::UniformDecl*>(item.get())) {
            generateUniform(*uniform);
        } else if (auto texture = dynamic_cast<const phoskia::TextureDecl*>(item.get())) {
            generateTexture(*texture);
        }
    }

    // Second pass: generate code
    for (const auto& item : material.declarations) {
        if (auto prop = dynamic_cast<const phoskia::PropertyDecl*>(item.get())) {
            generateProperty(*prop);
        } else if (auto shading = dynamic_cast<const phoskia::ShadingFunc*>(item.get())) {
            generateShading(*shading);
        }
    }

    _output += "[" + blockName + "]\n\n";
}

void AYBGFXConverter::generateProperty(const phoskia::PropertyDecl& prop) {
    // Property becomes a uniform in BGFX
    _output += "uniform vec4 " + prop.name + " = ";

    if (auto lit = dynamic_cast<const phoskia::LiteralExpr*>(prop.initializer.get())) {
        std::visit([this](auto&& arg) {
            using T = std::decay_t<decltype(arg)>;
            if constexpr (std::is_same_v<T, float>) {
                _output += std::to_string(arg);
            } else if constexpr (std::is_same_v<T, int>) {
                _output += std::to_string(arg);
            } else if constexpr (std::is_same_v<T, bool>) {
                _output += arg ? "1.0" : "0.0";
            }
        }, lit->value);
    } else {
        _output += "0.0";
    }

    _output += ";\n";
}

void AYBGFXConverter::generateUniform(const phoskia::UniformDecl& uniform) {
    BGFXUniform u;
    u.name = uniform.name;
    u.type = uniform.type;
    _uniforms.push_back(u);

    _output += "uniform " + uniform.type + " " + uniform.name + ";\n";
}

void AYBGFXConverter::generateTexture(const phoskia::TextureDecl& texture) {
    BGFXTexture t;
    t.name = texture.name;
    t.binding = static_cast<uint8_t>(_textures.size());
    _textures.push_back(t);

    _output += "texture2d " + texture.name + ";\n";
}

void AYBGFXConverter::generateShading(const phoskia::ShadingFunc& shading) {
    _output += "\nvoid main() {\n";

    for (const auto& stmt : shading.body) {
        if (auto let = dynamic_cast<const phoskia::LetStmt*>(stmt.get())) {
            _output += "    let " + let->name + " = ";
            generateExpr(*let->initializer);
            _output += ";\n";
        } else if (auto ret = dynamic_cast<const phoskia::ReturnStmt*>(stmt.get())) {
            _output += "    gl_FragColor = ";
            if (ret->value) {
                generateExpr(*ret->value);
            }
            _output += ";\n";
        } else if (auto expr = dynamic_cast<const phoskia::ExprStmt*>(stmt.get())) {
            _output += "    ";
            generateExpr(*expr->expr);
            _output += ";\n";
        }
    }

    _output += "}\n";
}

void AYBGFXConverter::generateExpr(const phoskia::Expr& expr) {
    if (auto binary = dynamic_cast<const phoskia::BinaryExpr*>(&expr)) {
        generateExpr(*binary->left);
        _output += " " + binary->op.lexeme + " ";
        generateExpr(*binary->right);
    } else if (auto unary = dynamic_cast<const phoskia::UnaryExpr*>(&expr)) {
        _output += unary->op.lexeme;
        generateExpr(*unary->operand);
    } else if (auto call = dynamic_cast<const phoskia::CallExpr*>(&expr)) {
        if (auto callee = dynamic_cast<const phoskia::IdentifierExpr*>(call->callee.get())) {
            _output += callee->name + "(";
        } else {
            _output += "(";
        }
        for (size_t i = 0; i < call->args.size(); ++i) {
            if (i > 0) _output += ", ";
            generateExpr(*call->args[i]);
        }
        _output += ")";
    } else if (auto id = dynamic_cast<const phoskia::IdentifierExpr*>(&expr)) {
        _output += id->name;
    } else if (auto lit = dynamic_cast<const phoskia::LiteralExpr*>(&expr)) {
        std::visit([this](auto&& arg) {
            using T = std::decay_t<decltype(arg)>;
            if constexpr (std::is_same_v<T, float>) {
                _output += std::to_string(arg);
            } else if constexpr (std::is_same_v<T, int>) {
                _output += std::to_string(arg);
            } else if constexpr (std::is_same_v<T, bool>) {
                _output += arg ? "true" : "false";
            }
        }, lit->value);
    } else if (auto member = dynamic_cast<const phoskia::MemberExpr*>(&expr)) {
        generateExpr(*member->object);
        _output += "." + member->member;
    } else if (auto index = dynamic_cast<const phoskia::IndexExpr*>(&expr)) {
        generateExpr(*index->object);
        _output += "[";
        generateExpr(*index->index);
        _output += "]";
    }
}

} // namespace ayt::shader
